[O2B-941] Add filtering to environment log api route
AliceO2Group/Bookkeeping pull request #1086
Opened 2023-08-07 19:08 UTC by emilyslade123

#### I have a JIRA ticket
- [x] branch and/or PR name(s) include(s) JIRA ID
- [ ] issue has "Fix version" assigned
- [x] issue "Status" is set to "In review"
- [x] PR labels are selected

Changes made to the database:
- API route for logs accepts filtering on environments

2023-08-24 10:15 UTC, martinboulais requested changes

2023-08-24 10:15 UTC, martinboulais commented on lib/usecases/log/GetAllLogsUseCase.js
> +            if (filter && filter.environments && filter.environments.values.length > 0) {
You can use `?.` here (on backend only for now)
`filter?.environment?.values?.length > 0`

2023-08-24 11:53 UTC, emilyslade123 commented on lib/server/services/environment/getAllEnvironmentsByTextOrFail.js
> +const getAllEnvironmentsByTextOrFail = async (environmentsTexts) => {
Forgot to delete this file

2023-08-25 05:46 UTC, martinboulais approved these changes

2023-08-25 12:56 UTC, merged