[O2B-989] - filtering runs by updatedAt
AliceO2Group/Bookkeeping pull request #1147
Opened 2023-09-08 13:29 UTC by xsalonx

#### I have a JIRA ticket
- [x] branch and/or PR name(s) include(s) JIRA ID
- [ ] issue has "Fix version" assigned
- [x] issue "Status" is set to "In review"
- [x] PR labels are selected

Notable changes for users:
- NA

Notable changes for developers:
- add support for `/api/runs` endpoint to filter on `updatedAt`

Changes made to the database:
- NA

2023-09-08 13:48 UTC, xsalonx commented on test/utilities/setRunsTimestamps.js
> +    return Promise.all(dbPromises);
this way, because,
- update, upsert methods doesn't work
- creating new run breaks other tests

2023-09-11 10:03 UTC, martinboulais requested changes

2023-09-11 10:03 UTC, martinboulais commented on test/utilities/resetDatabaseContent.js
>  };
A function named resetDatabaseContent should only reset database content to its default state, not do anything else.

2023-09-11 10:03 UTC, martinboulais commented on test/utilities/setRunsTimestamps.js
> +const setRunsTimestamps = async () => {
When you name function, think that this function name will be suggested in auto completion. 
`setRunsTimestamp` is way too generic to be exported as is, especially when it's a test function.

2023-09-12 12:04 UTC, closed without merging