[O2B-455] add flp home button
AliceO2Group/Bookkeeping pull request #1222
Opened 2023-11-02 13:46 UTC by xsalonx

#### I have a JIRA ticket
- [x] branch and/or PR name(s) include(s) JIRA ID
- [x] issue has "Fix version" assigned
- [ ] issue "Status" is set to "In review"
- [x] PR labels are selected

Notable changes for users:
- TODO

Notable changes for developers:
- TODO

Changes made to the database:
- NA

2023-11-07 13:45 UTC, martinboulais requested changes

2023-11-07 13:58 UTC, xsalonx commented on lib/public/components/NavBar/index.js
> +const aliFlpReferenceTab = (conf) => absoluteFrontLink(
done

2023-11-07 13:58 UTC, xsalonx commented on lib/public/components/NavBar/index.js
> + * @returns {vnode} returns tab
done

2023-11-07 13:59 UTC, xsalonx commented on lib/public/components/NavBar/index.js
> +    } }),
done

2023-11-07 13:59 UTC, xsalonx commented on lib/public/components/NavBar/index.js
> +        class: 'btn btn-group-item',
done

2023-11-07 13:59 UTC, xsalonx commented on lib/public/components/NavBar/index.js
> +import { getAliFlpReferencesConfiguration } from '../../services/externalRouting/getFlpIndexLinks.js';
done

2023-11-09 11:04 UTC, martinboulais commented on lib/public/components/NavBar/index.js
> + * @returns {vnode} returns tab
Not entierly. Scalar in lowercase

2023-11-09 11:19 UTC, xsalonx commented on lib/public/components/NavBar/index.js
> +import { getAliFlpReferencesConfiguration } from '../../services/externalRouting/getFlpIndexLinks.js';
deleted

2023-11-10 08:58 UTC, martinboulais approved these changes

2023-11-10 09:12 UTC, merged