[O2B-1043] Add pre-filled options for time range filter
AliceO2Group/Bookkeeping pull request #1242
Opened 2023-11-17 12:27 UTC by martinboulais

#### I have a JIRA ticket
- [X] branch and/or PR name(s) include(s) JIRA ID
- [X] issue has "Fix version" assigned
- [X] issue "Status" is set to "In review"
- [X] PR labels are selected

Notable changes for users:
- Added pre-fill options to the time filter

2023-11-22 16:22 UTC, xsalonx requested changes
I think there it can be a bit improved:

1. After selecting e.g. year 2022, still, there is title `Efficiency - 2023`, what is a bit misleading (the same for the page `lhc-fill-overview`)
2. After setting a week and changing to month that the given week dosen't belong to, the week number remains the same, for me it should not.
3. Maybe it's intended because of transforming to locale time, to be confirmed, if I choose e.g. some year I can see it is from 01:00 am to 01:00 am next year, should it be like this?
4. I suppose that months grid, present last twelve months. If so current solution with putting year at the right side of month name might be not very nice after reaching half of the next year. I would propose to mark year they belong to by setting some colour of background for particular month (or text, to be considered). Then years' tabs above might be styled as well with appropriate colours. 
![Screenshot 2023-11-22 at 16 58 32](https://github.com/AliceO2Group/Bookkeeping/assets/65893715/70a29894-d630-4ad1-afad-a56bd0905b75)
![Screenshot 2023-11-22 at 16 56 22](https://github.com/AliceO2Group/Bookkeeping/assets/65893715/74395893-cd7b-4844-806f-31b5d103b402)
![Screenshot 2023-11-22 at 16 56 02](https://github.com/AliceO2Group/Bookkeeping/assets/65893715/0f24a9b2-600d-4401-a09b-6d957ca8b83b)

2023-11-23 09:03 UTC, xsalonx requested changes

2023-11-23 09:24 UTC, xsalonx requested changes
Also, it's not very elegant that the date selection grid is 'leaky', hoovering affects underlying chart
![image](https://github.com/AliceO2Group/Bookkeeping/assets/65893715/9dd2b463-9465-4bf3-997d-7b7e3219fbca)

2023-11-23 11:23 UTC, xsalonx submitted a review, later dismissed

2023-11-23 11:23 UTC, martinboulais commented on lib/public/components/Filters/common/filters/timeRangeFilter.js
> +        }
I understand the point of view, I propose to merge as is for now and we discuss this further in a future PR

2023-11-23 11:26 UTC, martinboulais commented on lib/public/components/Filters/common/filters/timeRangeFilter.js
> + * @param {function} onChange function called with the clicked period
Agree, done

2023-11-23 11:29 UTC, xsalonx commented on lib/public/components/Filters/common/filters/timeRangeFilter.js
> +        }
agree

2023-11-23 11:40 UTC, merged