[O2B-1078] runs overview extraction
AliceO2Group/Bookkeeping pull request #1285
Opened 2023-12-07 11:09 UTC by xsalonx

<!--
Thank you for your pull request!
#### I have a JIRA ticket
- [ ] branch and/or PR name(s) include(s) JIRA ID
- [ ] issue has "Fix version" assigned
- [ ] issue "Status" is set to "In review"
- [ ] PR labels are selected

Notable changes for users:
- NA

Notable changes for developers:
- TODO

Changes made to the database:
- NA

2023-12-07 16:57 UTC, martinboulais requested changes

2023-12-07 16:57 UTC, martinboulais commented on lib/public/views/Home/Overview/index.js
> +const HomeOverviewScreen = ({ logs: logsModel, runs: { overviewModel: runsOverviewModel } }) => {
Doing so, I would rather take two parameters: logsModel and runsOverviewModel
Doing so, you are independent from the Model structure

2023-12-08 09:19 UTC, xsalonx commented on lib/public/views/Runs/RunsModel.js
> +export default class RunsModel extends Observable {
but, @type in model removed, it's redundant

2023-12-08 09:33 UTC, martinboulais approved these changes

2023-12-08 09:34 UTC, merged