[O2B-1079] Fetch run number that includes a specific substring
AliceO2Group/Bookkeeping pull request #1289
Opened 2023-12-11 20:44 UTC by saifrashed

#### I have a JIRA ticket
- [x] branch and/or PR name(s) include(s) JIRA ID
- [ ] issue has "Fix version" assigned
- [ ] issue "Status" is set to "In review"
- [x] PR labels are selected

Notable changes for users:
- New filter option (not yet implemented in the front end)

Notable changes for developers:
- Added field in filter DTO for runs
- Added a conditional bock for filter includes new filter on runs
- Find run numbers with given integer as substring
- Created new test

2023-12-12 09:25 UTC, graduta submitted a review, later dismissed
Hi @saifrashed ,

You should have a look to use and extend the existing field `runNumbers` instead of adding a new parameter. 
The filter should be enriched so that it uses the same parameter. Moreover, it should not make an extra query to find those.

2024-01-09 13:43 UTC, martinboulais commented
I think that making LIKE search on all substring will be hard to understand for user. Because if you want runs 1 & 3 (typing `1, 3`), you will also have run 11, 10, 31, 21 and so on. 
I propose, for start, to apply like only if there is no `,`. And if there is, search using oneof.
In a next step, we can think of allowing user to put `*` or `%` to put the fuzzy find even in comma separated lists, such as `123*, 234*` for example. But, this would be another ticket and need to be discussed further.

2024-01-09 13:43 UTC, martinboulais commented
I think that making LIKE search on all substring will be hard to understand for user. Because if you want runs 1 & 3 (typing `1, 3`), you will also have run 11, 10, 31, 21 and so on. 
I propose, for start, to apply like only if there is no `,`. And if there is, search using oneof.
In a next step, we can think of allowing user to put `*` or `%` to put the fuzzy find even in comma separated lists, such as `123*, 234*` for example. But, this would be another ticket and need to be discussed further.

2024-01-17 12:10 UTC, saifrashed commented on lib/usecases/run/GetAllRunsUseCase.js
> +                }
I have implemented the improved solution, thank you for the feedback. The previous solution did not make use of the already splitted runNumberList.

2024-01-18 08:42 UTC, martinboulais requested changes

2024-01-18 08:42 UTC, martinboulais commented on test/public/runs/overview.test.js
>      it('should successfully filter on a list of run numbers and inform the user about it', async () => {
Please add tests here on the substring filter, and same for the API test (runs api)

2024-01-22 09:07 UTC, martinboulais approved these changes

2024-01-22 13:09 UTC, merged