[O2B-1107] Filter on environment id
AliceO2Group/Bookkeeping pull request #1326
Opened 2024-01-12 14:42 UTC by CollinHva

#### I have a JIRA ticket
- [ ] branch and/or PR name(s) include(s) JIRA ID
- [ ] issue has "Fix version" assigned
- [ ] issue "Status" is set to "In review"
- [ ] PR labels are selected

Notable changes for users:
- none

Notable changes for developers:
- API now allows filtering on get all environments

Changes made to the database:
- none

2024-01-16 11:24 UTC, martinboulais requested changes

2024-01-16 11:24 UTC, martinboulais commented on lib/usecases/environment/GetAllEnvironmentsUseCase.js
> +                    queryBuilder.literalWhere('id LIKE :filter', { filter: `%${filters[0]}%` });
You should use `substring` instead

2024-01-16 13:05 UTC, CollinHva commented on lib/usecases/environment/GetAllEnvironmentsUseCase.js
> +                    queryBuilder.literalWhere('id LIKE :filter', { filter: `%${filters[0]}%` });
done

2024-01-17 07:22 UTC, martinboulais requested changes

2024-01-17 07:22 UTC, martinboulais commented on test/api/environments.test.js
>      });
Please add tests: without filter, with several env ids

2024-01-17 08:04 UTC, CollinHva commented on test/api/environments.test.js
>      });
done

2024-01-18 08:29 UTC, martinboulais approved these changes

2024-01-18 09:12 UTC, merged