[O2B-1138] Implement Data Pass per Simulation Pass view
AliceO2Group/Bookkeeping pull request #1373
Opened 2024-01-30 11:54 UTC by xsalonx

#### I have a JIRA ticket
- [x] branch and/or PR name(s) include(s) JIRA ID
- [x] issue has "Fix version" assigned
- [ ] issue "Status" is set to "In review"
- [x] PR labels are selected

Notable changes for users:
- Add Data Passes per Simulation Pass view

Notable changes for developers:
- NA

Changes made to the database:
- NA

2024-02-15 12:17 UTC, xsalonx commented
To be merged after https://github.com/AliceO2Group/Bookkeeping/pull/1370

2024-03-08 15:24 UTC, xsalonx commented
To be merged after https://github.com/AliceO2Group/Bookkeeping/pull/1436

2024-04-02 16:31 UTC, martinboulais requested changes

2024-04-02 16:31 UTC, martinboulais commented on lib/server/controllers/dataPasses.controller.js
> +                simulationPassIds: Joi.array().items(Joi.string()),
Shouldn't it be an array of numbers?

2024-04-02 16:31 UTC, martinboulais commented on test/public/defaults.js
> +    expect(validator(actualInnerText), `"${actualInnerText}" is invalid with respect of given validator`).to.be.true;
Nope

2024-04-02 16:35 UTC, xsalonx commented on lib/public/views/DataPasses/PerSimulationPassOverview/DataPassesPerSimulationPassOverviewModel.js
> +    get namesFilterModel() {
applied

2024-04-02 16:47 UTC, xsalonx commented on lib/public/views/DataPasses/PerSimulationPassOverview/DataPassesPerSimulationPassOverviewPage.js
> +    const commonTitle = h('h2', { style: 'white-space: nowrap;' }, 'Data Passes per MC');
moved to app.css, when it isn't styled this way, during loading, first part of header is different position than when data are loaded

2024-04-02 16:48 UTC, xsalonx commented on lib/public/views/DataPasses/PerSimulationPassOverview/DataPassesPerSimulationPassOverviewPage.js
> +                    NotAsked: () => [commonTitle, tooltip(h('.f3', iconWarning()), 'No data was asked for')],
simulation pass, it's part of header (data passes Per Simulation Pass)

2024-04-02 16:49 UTC, xsalonx commented on lib/server/controllers/dataPasses.controller.js
> +                simulationPassIds: Joi.array().items(Joi.string()),
should be, fixed

2024-04-03 05:24 UTC, xsalonx commented on test/public/defaults.js
> +    expect(validator(actualInnerText), `"${actualInnerText}" is invalid with respect of given validator`).to.be.true;
hmm, some merge artifact, pruned

2024-04-03 08:04 UTC, martinboulais requested changes

2024-04-03 08:04 UTC, martinboulais commented on lib/public/views/DataPasses/PerSimulationPassOverview/DataPassesPerSimulationPassOverviewPage.js
> +                    NotAsked: () => [commonTitle, tooltip(h('.f3', iconWarning()), 'No data was asked for')],
My bad I read data pass instead of data...

2024-04-03 08:05 UTC, martinboulais commented on lib/public/views/DataPasses/PerSimulationPassOverview/DataPassesPerSimulationPassOverviewPage.js
> +    const commonTitle = h('h2', { style: 'white-space: nowrap;' }, 'Data Passes per MC');
nowrap is very dangerous, especially on small screen, you should try to find a way to solve your issue using flex configuration instaed

2024-04-03 09:07 UTC, xsalonx commented on lib/public/views/DataPasses/PerSimulationPassOverview/DataPassesPerSimulationPassOverviewPage.js
> +    const commonTitle = h('h2', { style: 'white-space: nowrap;' }, 'Data Passes per MC');
found simple solution, removed

2024-04-03 09:11 UTC, xsalonx commented on lib/public/views/DataPasses/PerSimulationPassOverview/DataPassesPerSimulationPassOverviewModel.js
> +    get namesFilterModel() {
applied, needed to change in DataPassesPerLhcPeriod model

2024-04-03 09:25 UTC, martinboulais approved these changes

2024-04-03 09:43 UTC, merged