[O2B-1173] Remove TST detector from RCT views
AliceO2Group/Bookkeeping pull request #1427
Opened 2024-02-26 14:15 UTC by xsalonx

#### I have a JIRA ticket
- [x] branch and/or PR name(s) include(s) JIRA ID
- [x] issue has "Fix version" assigned
- [x] issue "Status" is set to "In review"
- [x] PR labels are selected

Notable changes for users:
- Remove TST detector from Runs Per Data Pass and LHC Period views

Notable changes for developers:
- NA

Changes made to the database:
- NA

2024-02-27 13:02 UTC, xsalonx commented on lib/public/views/Runs/ActiveColumns/runDetectorsActiveColumns.js
> + * @param {Detector[]|null} detectors detectors list ('TST' is excluded even if it is provided)
moved filtering to models

2024-02-29 09:28 UTC, martinboulais requested changes

2024-03-01 08:29 UTC, xsalonx commented on lib/public/views/Runs/RunPerDataPass/RunsPerDataPassOverviewModel.js
> +            const detectors = (await detectorsProvider.getAll()).filter(({ name }) => name !== TST_DETECTOR_NAME);
applied

2024-03-01 10:32 UTC, martinboulais approved these changes

2024-03-01 11:04 UTC, merged