[O2B-953] Log Creation input fields autofill when needed
AliceO2Group/Bookkeeping pull request #1438
Opened 2024-03-01 14:58 UTC by AnoeBanoe

#### I have a JIRA ticket
- [x] branch and/or PR name(s) include(s) JIRA ID
- [x] issue has "Fix version" assigned
- [x] issue "Status" is set to "In review"
- [ ] PR labels are selected

Notable changes for users:
- When creating a log from either the environments or runs page, the existing data autofills in the form

2024-03-06 06:51 UTC, martinboulais requested changes

2024-03-06 14:35 UTC, AnoeBanoe commented on lib/public/views/Logs/LogsModel.js
> +
done

2024-03-06 14:36 UTC, AnoeBanoe commented on lib/public/views/Logs/LogsModel.js
> +            relations.runNumbers = this._parseNumbers(runNumbers);
done

2024-03-06 14:36 UTC, AnoeBanoe commented on lib/public/views/Runs/Details/runDetailsComponent.js
> +        const linkOptions = {
done

2024-03-06 18:17 UTC, martinboulais requested changes

2024-03-06 18:17 UTC, martinboulais commented on lib/public/views/Logs/LogsModel.js
> +     * @param {string} commaSeparatedString The comma-separated string of numbers to parse
Maybe `commaSeparatedNumbers` instead?

2024-03-06 18:17 UTC, martinboulais commented on lib/public/views/Logs/LogsModel.js
>              relations.environmentIds = Array.isArray(environmentIds) ? environmentIds : [environmentIds];
If you change the docblock, this should be changed. If you can't have an array, you should probably actually split the environmentIds here too (no conversion to number though)

2024-03-08 10:01 UTC, martinboulais requested changes

2024-03-08 10:01 UTC, martinboulais commented on lib/public/views/Logs/LogsModel.js
> +            relations.environmentIds = environmentIds.split(',');
```suggestion
            relations.environmentIds = environmentIds.split(',').map((environmentId) => environmentId.trim());
```

2024-03-08 10:05 UTC, AnoeBanoe commented on lib/public/views/Logs/LogsModel.js
> +            relations.environmentIds = environmentIds.split(',');
done

2024-03-08 10:35 UTC, martinboulais approved these changes

2024-03-08 11:02 UTC, merged