[O2B-1155] Add QC flags per simulation pass creation
AliceO2Group/Bookkeeping pull request #1513
Opened 2024-04-15 11:07 UTC by martinboulais

#### I have a JIRA ticket
- [X] branch and/or PR name(s) include(s) JIRA ID
- [X] issue has "Fix version" assigned
- [X] issue "Status" is set to "In review"
- [X] PR labels are selected

Notable changes for users:
- Added QC flag creation for simulation pass

2024-04-15 11:40 UTC, xsalonx requested changes

2024-04-15 11:40 UTC, xsalonx commented on test/public/qcFlags/forSimulationPassCreation.test.js
> +        await goToPage(page, 'qc-flag-creation-for-simulation-pass', { queryParameters: {
missing ...

2024-04-15 11:40 UTC, xsalonx commented on lib/public/views/QcFlags/Create/forSimulationPass/QcFlagCreationForSimulationPassModel.js
> +     * @param {function(number,*)} onCreationSuccess callback in case of successful QC flag creation
Maybe update related models' docs?

2024-04-15 12:18 UTC, martinboulais commented on test/public/qcFlags/forSimulationPassCreation.test.js
> +        await goToPage(page, 'qc-flag-creation-for-simulation-pass', { queryParameters: {
Fixed

2024-04-16 07:09 UTC, xsalonx approved these changes

2024-04-16 07:30 UTC, merged