[O2B-1221] Reduce links display to count badges
AliceO2Group/Bookkeeping pull request #1526
Opened 2024-04-22 11:14 UTC by xsalonx

#### I have a JIRA ticket
- [x] branch and/or PR name(s) include(s) JIRA ID
- [x] issue has "Fix version" assigned
- [x] issue "Status" is set to "In review"
- [x] PR labels are selected

Notable changes for users:
- Reduced links to RCT views to counts badges

Notable changes for developers:
- NA

Changes made to the database:
- NA

2024-04-22 11:14 UTC, xsalonx commented
To be merged after https://github.com/AliceO2Group/Bookkeeping/pull/1525

2024-04-23 09:25 UTC, martinboulais requested changes

2024-04-23 09:25 UTC, martinboulais commented on lib/public/views/DataPasses/ActiveColumns/dataPassesActiveColumns.js
> +                    h('.flex-row.g3', h('.f6.badge.bg-gray-light.black', runsCount)),
You can simply display them as normal links
(btw if you have only one child, you can remove the flex-row and gap)

2024-04-24 14:02 UTC, martinboulais approved these changes

2024-05-10 12:21 UTC, graduta approved these changes

2024-05-10 12:39 UTC, merged