[O2B-1298] Mark deleted ML productions
AliceO2Group/Bookkeeping pull request #1637
Opened 2024-07-02 09:43 UTC by xsalonx

#### I have a JIRA ticket
- [x] branch and/or PR name(s) include(s) JIRA ID
- [x] issue has "Fix version" assigned
- [x] issue "Status" is set to "In review"
- [x] PR labels are selected

Notable changes for users:
- Marked data passes deleted from ML with green color and icon

Notable changes for developers:
- NA

Changes made to the database:
- NA

2024-07-02 12:17 UTC, martinboulais requested changes

2024-07-02 12:17 UTC, martinboulais commented on lib/server/monalisa-synchronization/MonAlisaSynchronizer.js
> +            .map((descriptionToId) => Object.entries(descriptionToId)).flatMap((_) => _));
Why is this parameter named `_` ????

2024-07-02 12:22 UTC, xsalonx commented on lib/public/views/DataPasses/ActiveColumns/dataPassesActiveColumns.js
> +    { anchor: PopoverAnchors.BOTTOM_MIDDLE },
it's because of balloon, not another tooltip

2024-07-02 12:43 UTC, xsalonx commented on lib/database/adapters/DataPassVersionAdapter.js
> +            deletedFromMl,
applied

2024-07-02 12:46 UTC, xsalonx commented on lib/domain/entities/DataPassVersion.js
> + * @property {number} updatedAt
those are of type `number` (`bigint` to be precise), Date is in `Sequelize{Entity}`

2024-07-03 09:58 UTC, xsalonx commented on lib/public/views/DataPasses/ActiveColumns/dataPassesActiveColumns.js
> +    { anchor: PopoverAnchors.BOTTOM_MIDDLE },
refactored, differentiate state of deletion in name column

2024-07-03 09:58 UTC, xsalonx commented on lib/public/views/DataPasses/ActiveColumns/dataPassesActiveColumns.js
> +            ? badge(h('.flex-row.g1', [dataPassDeletedFromMlIcon, name]), { color: '#4caf50' })
it's success colour , refactored

2024-07-03 09:58 UTC, xsalonx commented on lib/public/views/DataPasses/ActiveColumns/dataPassesActiveColumns.js
> +            h(deletedFromMl ? '.success' : '', h('.flex-row.g1', [deletedFromMl ? dataPassDeletedFromMlIcon : null, description]))),
refactored

2024-07-03 10:02 UTC, xsalonx commented on lib/server/monalisa-synchronization/MonAlisaSynchronizer.js
> +                    this._doesDataPassVersionNeedUpdate(monalisaDataPassVersion, dataPassVersionsLastSeenAndId));
refactored

2024-07-03 10:02 UTC, xsalonx commented on lib/server/monalisa-synchronization/MonAlisaSynchronizer.js
> +            .map((descriptionToId) => Object.entries(descriptionToId)).flatMap((_) => _));
because it identity, anyway refactored

2024-07-04 10:18 UTC, martinboulais requested changes

2024-07-04 10:18 UTC, martinboulais commented on lib/public/views/DataPasses/format/formatDataPassName.js
> +            { color: 'var(--color-success)' },
Please apply a style instead!

2024-07-04 10:22 UTC, xsalonx commented on lib/public/views/DataPasses/format/formatDataPassName.js
> +            { color: 'var(--color-success)' },
If I apply style, contrast won't work

2024-07-04 12:09 UTC, martinboulais approved these changes

2024-07-04 12:23 UTC, merged