[O2B-1365] Disable GAQ summary if not all detectors have full coverage
AliceO2Group/Bookkeeping pull request #1784
Opened 2024-10-14 09:13 UTC by xsalonx

#### I have a JIRA ticket
- [ ] branch and/or PR name(s) include(s) JIRA ID
- [ ] issue has "Fix version" assigned
- [ ] issue "Status" is set to "In review"
- [ ] PR labels are selected

Notable changes for users:
-

Notable changes for developers:
-

Changes made to the database:
-

2024-11-25 12:48 UTC, martinboulais requested changes

2024-11-25 12:48 UTC, martinboulais commented on test/public/runs/runsPerDataPass.overview.test.js
> +        await goToPage(page, 'runs-per-data-pass', { queryParameters: { dataPassId: 1 } });
Same, we should avoid goToPage

2024-11-27 13:32 UTC, xsalonx commented on lib/server/services/qualityControlFlag/QcFlagService.js
> +
Why not to wrap single-for-loop with this filling method which occur in `getGaqSummary(...)` ?

2024-11-27 13:37 UTC, xsalonx commented on test/public/runs/runsPerDataPass.overview.test.js
> +        await goToPage(page, 'runs-per-data-pass', { queryParameters: { dataPassId: 3 } });
fixed

2024-11-27 14:48 UTC, xsalonx commented on lib/server/services/qualityControlFlag/QcFlagService.js
>  };
done

2024-11-27 14:51 UTC, xsalonx commented on lib/database/repositories/QcFlagRepository.js
> +                -- Two selects for runs' timestamps (in case QC flag's eff. period doesn't start at run's start or end at run's end )
applied in xsalonx/gaq/O2B-1365/disable-gaq-if-detector-is-missing---with-views

2025-06-04 22:14 UTC, closed without merging