fixed doubling log entries
AliceO2Group/Bookkeeping pull request #349
Opened 2021-04-19 19:02 UTC by io112

2021-04-21 09:58 UTC, DimitrySteenkamer requested changes
Both the log-overview and tag-overview infinite mode selector now works correctly. When infinite rows per page are selected. It now correctly adds the remaining rows to the already existing rows.

But the run-overview still has the same problem. When infinite rows per page are selected, it adds all the rows to the already existing ones.

2021-04-21 10:29 UTC, DimitrySteenkamer reviewed
It works, the bug has been fixed in the tag, runs and logs overview

2021-04-21 10:36 UTC, DimitrySteenkamer approved these changes

2021-04-24 11:25 UTC, io112 commented
There is some problems going from the current master state after [db-namig-fix was merged](https://github.com/AliceO2Group/Bookkeeping/runs/2426350613).

2021-05-04 13:32 UTC, merged