[O2B-577] Block run creation on duplicate run number
AliceO2Group/Bookkeeping pull request #597
Opened 2022-05-19 13:58 UTC by martinboulais

#### I have a JIRA ticket
- [X] branch and/or PR name(s) include(s) JIRA ID
- [ ] issue has "Fix version" assigned
- [X] issue "Status" is set to "In review"
- [X] PR labels are selected

2022-05-24 15:27 UTC, graduta requested changes

2022-05-24 17:10 UTC, martinboulais commented on test/usecases/run/StartRunUseCase.test.js
> +        const { result, error } = await new StartRunUseCase()
Yes, added

2022-06-13 20:15 UTC, graduta approved these changes

2022-06-13 20:16 UTC, graduta commented
Nice job! 👍 
Feel free to merge once you update with `master`

2022-06-14 07:47 UTC, merged