[O2B-511] Run filters should accept operators
AliceO2Group/Bookkeeping pull request #615
Opened 2022-06-07 14:04 UTC by martinboulais

#### I have a JIRA ticket
- [X] branch and/or PR name(s) include(s) JIRA ID
- [ ] issue has "Fix version" assigned
- [X] issue "Status" is set to "In review"
- [X] PR labels are selected

2022-06-13 20:59 UTC, graduta requested changes
I found an interesting user scenario which it is not desirable.
1. Open Run-Overview Page
2. Open Filters
3. Select an operator before adding a value for a numerical filter;
This will transition the page to an error state due to `Invalid Attribute: "query.filter.nDetectors.limit" must be a number`

2022-06-13 20:59 UTC, graduta commented on lib/public/components/Filters/components/amountFilter.js
> +/**
I believe the import should come after the `licence` tag and comment, right?

2022-06-14 12:23 UTC, martinboulais commented
> I found an interesting user scenario which it is not desirable.
> 
>     1. Open Run-Overview Page
> 
>     2. Open Filters
> 
>     3. Select an operator before adding a value for a numerical filter;
>        This will transition the page to an error state due to `Invalid Attribute: "query.filter.nDetectors.limit" must be a number`

I fixed it

2022-06-15 09:31 UTC, graduta approved these changes

2022-06-15 09:40 UTC, merged