Bug/environment loading times
AliceO2Group/Bookkeeping pull request #708
Opened 2022-08-30 12:05 UTC by JikHuijberts

#### I DON'T have JIRA ticket
- [x] explain what this PR does
- [x] if it is a new feature, explain how you plan to use it
- [x] tests are added
- [x] documentation was updated or added

When fetching the environments the run will be a minified object to reduce the time it takes to map out all the values.

2022-08-31 06:21 UTC, martinboulais requested changes

2022-08-31 06:21 UTC, martinboulais commented on spec/openapi-source.yaml
> +          description: A inteber pointing to the run number
typo

2022-08-31 11:46 UTC, JikHuijberts commented on spec/openapi-source.yaml
> +          description: A inteber pointing to the run number
done

2022-09-06 12:27 UTC, martinboulais approved these changes

2022-09-06 12:30 UTC, merged